# -*- coding: utf-8 -*-
"""
Port contract for vector store retrieval (Aequitas-MAS).

Defines the VectorStorePort Protocol that all infrastructure adapters MUST
implement. This is the Dependency Inversion Principle (DIP) boundary: agents
and tools depend exclusively on this interface, never on concrete SDKs.

The Macro Agent injects a VectorStorePort at runtime, enabling infrastructure
to be swapped (OpenSearch, Pinecone, in-memory mock) without touching agent
logic.

Also provides NullVectorStore — the Null Object Pattern implementation used
as a safe default when no vector store is configured (local/offline mode).
"""

from typing import Protocol, runtime_checkable


@runtime_checkable
class VectorStorePort(Protocol):
    """
    Port interface for semantic vector search.

    Any concrete adapter (e.g., OpenSearchAdapter) must satisfy this
    structural contract. By using typing.Protocol, compliance is verified
    structurally — no explicit inheritance required.
    """

    def search_macro_context(self, query: str, top_k: int = 5) -> list[dict]:
        """
        Retrieve the top-k most semantically similar macroeconomic documents.

        Args:
            query: The natural language query or hypothetical document
                   generated by the HyDE pipeline to anchor the search.
            top_k: Maximum number of documents to return. Defaults to 5.

        Returns:
            A list of result dicts. Each dict MUST contain:
                - ``document_id`` (str): Unique identifier of the stored chunk.
                - ``source_url``  (str): Traceable origin URL (e.g., BCB, FED).
                - ``content``     (str): The raw text of the retrieved chunk.
                - ``score``       (float): Cosine similarity score [0.0, 1.0].
        """
        ...


class NullVectorStore:
    """
    Null Object Pattern implementation of VectorStorePort.

    Used as a safe default when OpenSearch is not configured (local/offline
    mode). Returns an empty list on every call, triggering Controlled
    Degradation in the Macro Agent without raising exceptions.

    This class satisfies VectorStorePort structurally — no inheritance needed.
    """

    def search_macro_context(self, query: str, top_k: int = 5) -> list[dict]:
        """Return empty results, triggering Controlled Degradation downstream."""
        return []
