# -*- coding: utf-8 -*-
"""
Port contract for vector store retrieval (Aequitas-MAS).

Defines the VectorStorePort Protocol that all infrastructure adapters MUST
implement. This is the Dependency Inversion Principle (DIP) boundary: agents
and tools depend exclusively on this interface, never on concrete SDKs.

The Macro Agent injects a VectorStorePort at runtime, enabling infrastructure
to be swapped (OpenSearch, Pinecone, in-memory mock) without touching agent
logic.

Also provides NullVectorStore — the Null Object Pattern implementation used
as a safe default when no vector store is configured (local/offline mode).
"""

from __future__ import annotations

from datetime import date
import math
from typing import Any, Optional, Protocol, runtime_checkable

from pydantic import BaseModel, ConfigDict, field_validator


class VectorSearchResult(BaseModel):
    """Immutable vector-retrieval payload returned by the search boundary."""

    model_config = ConfigDict(frozen=True)

    document_id: str
    source_url: str
    content: str
    score: float

    @field_validator("score", mode="before")
    @classmethod
    def validate_finite_score(cls, value: Any) -> float:
        """Safely coerce retrieval scores and reject NaN/Inf."""
        try:
            normalized = float(value)
        except (TypeError, ValueError) as exc:
            raise ValueError(f"Could not convert value '{value}' to float.") from exc

        if not math.isfinite(normalized):
            raise ValueError(f"Value '{value}' is not a valid finite number.")

        return normalized

    @field_validator("document_id", "source_url", "content", mode="before")
    @classmethod
    def normalize_optional_strings(cls, value: Optional[str]) -> str:
        """Degrade missing string fields to empty strings instead of None."""
        if value is None:
            return ""
        return str(value)


@runtime_checkable
class VectorStorePort(Protocol):
    """
    Port interface for semantic vector search.

    Any concrete adapter (e.g., OpenSearchAdapter) must satisfy this
    structural contract. By using typing.Protocol, compliance is verified
    structurally — no explicit inheritance required.
    """

    def search_macro_context(
        self,
        query: str,
        as_of_date: date,
        top_k: int = 5,
    ) -> list[VectorSearchResult]:
        """
        Retrieve the top-k most semantically similar macroeconomic documents.

        Args:
            query: The natural language query or hypothetical document
                   generated by the HyDE pipeline to anchor the search.
            as_of_date: Strict point-in-time reference used to constrain
                retrieval visibility.
            top_k: Maximum number of documents to return. Defaults to 5.

        Returns:
            A list of immutable ``VectorSearchResult`` objects containing
            ``document_id``, ``source_url``, ``content``, and ``score``.
        """
        ...


class NullVectorStore:
    """
    Null Object Pattern implementation of VectorStorePort.

    Used as a safe default when OpenSearch is not configured (local/offline
    mode). Returns an empty list on every call, triggering Controlled
    Degradation in the Macro Agent without raising exceptions.

    This class satisfies VectorStorePort structurally — no inheritance needed.
    """

    def search_macro_context(
        self,
        query: str,
        as_of_date: date,
        top_k: int = 5,
    ) -> list[VectorSearchResult]:
        """Return empty results, triggering Controlled Degradation downstream."""
        del query, as_of_date, top_k
        return []
