# -*- coding: utf-8 -*-
"""
Central state module for the Aequitas-MAS.

This file defines the data structure that circulates among the agents in the LangGraph.
Adhering to the "Zero Numerical Hallucination" principle, all financial metrics
use `decimal.Decimal` to ensure mathematical precision and avoid floating-point
errors from the `float` type.

Classes:
    GrahamMetrics: Pydantic schema for the Graham Agent's metrics.
    FisherAnalysis: Pydantic schema for the Fisher Agent's qualitative analysis.
    AgentState: Pydantic BaseModel representing the complete graph state.
"""
import operator
from decimal import Decimal, InvalidOperation
from typing import Annotated, List, Optional, Any

from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    field_validator,
)


# 1. PYDANTIC SCHEMAS (BOUNDARY VALIDATION)
# These schemas ensure that data generated by Tools or LLMs
# is mathematically correct before entering the state.


class GrahamMetrics(BaseModel):
    """
    Deterministic Value Investing metrics (Graham Agent).

    This class enforces the "Zero Numerical Hallucination" dogma by using
    `Decimal` for all financial calculations and preventing the entry of
    primitive `float` types.
    """

    model_config = ConfigDict(frozen=True, populate_by_name=True)

    # Strict ticker validation for market standard compliance.
    ticker: str = Field(
        ...,
        description="O código de negociação do ativo na bolsa B3.",
        pattern=r"^[A-Z0-9]{5,6}$",
    )

    # Campos financeiros obrigatórios para a fórmula de Graham.
    vpa: Optional[Decimal] = Field(None, description="Valor Patrimonial por Ação (VPA).")
    lpa: Optional[Decimal] = Field(None, description="Lucro por Ação (LPA).")

    # Optional fields that depend on calculations or data availability.
    price_to_earnings: Optional[Decimal] = Field(
        None, description="Índice Preço/Lucro (P/L)."
    )
    fair_value: Optional[Decimal] = Field(
        None, description="Valor intrínseco calculado pela fórmula de Graham."
    )
    margin_of_safety: Optional[Decimal] = Field(
        None, description="Margem de segurança percentual."
    )

    @field_validator(
        "vpa",
        "lpa",
        "price_to_earnings",
        "fair_value",
        "margin_of_safety",
        mode="before",
    )
    @classmethod
    def coerce_to_decimal(cls, v: Any) -> Optional[Decimal]:
        """
        Safely coerces inputs (str, int, float) to Decimal.

        This pre-processing validator ensures that any numerical data
        received from external sources (APIs, scraping) is converted to
        `Decimal` before Pydantic validation, avoiding the precision loss
        of the IEEE 754 standard.
        """
        if v is None:
            return None
        try:
            return Decimal(str(v))
        except (InvalidOperation, ValueError):
            raise ValueError(f"Não foi possível converter o valor '{v}' para Decimal.")


class FisherAnalysis(BaseModel):
    """Context and sentiment analysis (Fisher Agent)."""

    model_config = ConfigDict(frozen=True)

    sentiment_score: float = Field(
        ...,
        ge=-1,
        le=1,
        description="Pontuação de sentimento extraída das notícias (-1 a 1).",
    )
    key_risks: List[str] = Field(
        ..., description="Lista de principais riscos identificados."
    )
    # Ethical Traceability: Mandatory source citation.
    source_urls: List[str] = Field(
        default_factory=list, description="URLs das fontes usadas para a análise."
    )


class MacroAnalysis(BaseModel):
    """Holistic evaluation of the macroeconomic environment (Macro Agent)."""

    model_config = ConfigDict(frozen=True)

    trend_summary: str = Field(
        ..., description="Summary of the current macroeconomic trend."
    )
    interest_rate_impact: Optional[Decimal] = Field(
        None, description="Estimated impact of the interest rate (e.g., Selic/Fed Funds)."
    )
    inflation_outlook: Optional[str] = Field(
        None, description="Inflation outlook extracted from official minutes."
    )
    # Ethical Traceability: Mandatory source citation.
    source_urls: List[str] = Field(
        default_factory=list, description="URLs das fontes usadas para a análise."
    )

    @field_validator(
        "interest_rate_impact",
        mode="before",
    )
    @classmethod
    def coerce_to_decimal(cls, v: Any) -> Optional[Decimal]:
        """Safely coerces inputs to Decimal."""
        if v is None:
            return None
        try:
            return Decimal(str(v))
        except (InvalidOperation, ValueError):
            raise ValueError(f"Não foi possível converter o valor '{v}' para Decimal.")


# 2. GRAPH STATE DEFINITION (LANGGRAPH)
# The state is the "living object" that circulates among the agents.


class AgentState(BaseModel):
    """
    Representa o Estado Cognitivo Híbrido da Aequitas-MAS.

    Uses Reducers (`operator.add`) to manage the cumulative memory
    in `messages` and `audit_log`, allowing the history to be built
    incrementally with each step of the graph.
    """

    model_config = ConfigDict(frozen=True)

    # History of the conversation between the Supervisor and Specialists.
    messages: Annotated[list[BaseMessage], add_messages] = Field(default_factory=list)

    # Target ticker for the current analysis.
    target_ticker: str = Field(
        ...,
        description="O código de negociação do ativo na bolsa B3.",
        pattern=r"^[A-Z0-9]{5,6}$",
    )

    # Decision Tensors (Structured Data).
    # Optional because they are filled progressively.
    # None can indicate 'controlled failure' or 'not yet executed'.
    metrics: Optional[GrahamMetrics] = None
    qual_analysis: Optional[FisherAnalysis] = None
    macro_analysis: Optional[MacroAnalysis] = None

    # Audit Log from the Marks Agent (The Devil's Advocate).
    # Annotated + operator.add allows accumulating critiques without overwriting.
    audit_log: Annotated[List[str], operator.add] = Field(default_factory=list)
