# -*- coding: utf-8 -*-
"""
Core state module for the Aequitas-MAS.

This file defines the data structure that circulates among the agents in the LangGraph graph.
Adhering to the "Zero Numerical Hallucination" principle, all financial metrics
use `decimal.Decimal` to ensure mathematical precision and avoid floating-point
errors from the `float` type.

Classes:
    GrahamMetrics: Pydantic schema for the Graham Agent's metrics.
    FisherAnalysis: Pydantic schema for the Fisher Agent's qualitative analysis.
    AgentState: TypedDict representing the complete state of the graph.
"""
import operator
from decimal import Decimal, InvalidOperation
from typing import Annotated, List, Optional, TypedDict, Any

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    field_validator
)


# 1. PYDANTIC SCHEMAS (BOUNDARY VALIDATION)
# These schemas ensure that data generated by Tools or LLMs
# is mathematically correct before entering the state.

class GrahamMetrics(BaseModel):
    """
    Deterministic Value Investing metrics (Graham Agent).

    This class enforces the "Zero Numerical Hallucination" dogma by using
    `Decimal` for all financial calculations and preventing the entry of
    primitive `float` types.
    """
    model_config = ConfigDict(frozen=True, populate_by_name=True)

    # Strict validation of the ticker for market standard compliance.
    ticker: str = Field(
        ...,
        description="The asset's trading code on the B3 exchange.",
        pattern=r"^[A-Z0-9]{5,6}$"
    )

    # Mandatory financial fields for the Graham formula.
    vpa: Decimal = Field(..., description="Book Value Per Share.")
    lpa: Decimal = Field(..., description="Earnings Per Share.")

    # Optional fields that depend on calculations or data availability.
    price_to_earnings: Optional[Decimal] = Field(
        None, description="Price-to-Earnings (P/E) ratio."
    )
    fair_value: Optional[Decimal] = Field(
        None, description="Intrinsic value calculated by the Graham formula."
    )
    margin_of_safety: Optional[Decimal] = Field(
        None, description="Percentage margin of safety."
    )

    @field_validator(
        "vpa",
        "lpa",
        "price_to_earnings",
        "fair_value",
        "margin_of_safety",
        mode='before'
    )
    @classmethod
    def coerce_to_decimal(cls, v: Any) -> Optional[Decimal]:
        """
        Safely coerces inputs (str, int, float) to Decimal.

        This pre-processing validator ensures that any numerical data
        received from external sources (APIs, scraping) is converted to
        `Decimal` before Pydantic's validation, avoiding the precision
        loss of the IEEE 754 standard.
        """
        if v is None:
            return None
        try:
            return Decimal(str(v))
        except (InvalidOperation, ValueError):
            raise ValueError(f"Could not convert value '{v}' to Decimal.")

class FisherAnalysis(BaseModel):
    """Context and sentiment analysis (Fisher Agent)."""
    model_config = ConfigDict(frozen=True)

    sentiment_score: float = Field(
        ...,
        ge=-1,
        le=1,
        description="Sentiment score extracted from news (-1 to 1)."
    )
    key_risks: List[str] = Field(
        ..., description="List of identified key risks."
    )
    # Ethical Traceability: Mandatory source citation.
    source_urls: List[str] = Field(
        default_factory=list,
        description="URLs of the sources used for the analysis."
    )

# 2. GRAPH STATE DEFINITION (LANGGRAPH)
# The state is the "living object" that circulates among the agents.

class AgentState(TypedDict):
    """
    Represents the Hybrid Cognitive State of Aequitas-MAS.

    It uses Reducers (`operator.add`) to manage accumulative memory
    in `messages` and `audit_log`, allowing the history to be built
    incrementally at each step of the graph.
    """

    # Conversation history between the Supervisor and the Specialists.
    messages: Annotated[List[dict], operator.add]

    # Target ticker for the current analysis.
    target_ticker: str

    # Decision Tensors (Structured Data).
    # Optional because they are progressively filled by the agents.
    metrics: Optional[GrahamMetrics]
    qual_analysis: Optional[FisherAnalysis]

    # Audit Log from Agent Marks (The Devil's Advocate).
    # Annotated + operator.add allows accumulating critiques without overwriting.
    audit_log: Annotated[List[str], operator.add]

    # Routing control for the Supervisor.
    next_agent: str
