# -*- coding: utf-8 -*-
"""
Central state module for the Aequitas-MAS.

This file defines the data structure that circulates among the agents in the LangGraph.
Adhering to the "Controlled Degradation" principle, financial metrics are represented
as `Optional[float]` and validated to avoid non-finite values (NaN/Inf).

Classes:
    GrahamMetrics: Pydantic schema for the Graham Agent's metrics.
    FisherAnalysis: Pydantic schema for the Fisher Agent's qualitative analysis.
    PortfolioWeight: Pydantic schema for optimized ticker weights.
    CoreAnalysis: Pydantic schema for supervisor optimization output.
    AgentState: Pydantic BaseModel representing the complete graph state.
"""

import math
import operator
from typing import Annotated, Any, List, Optional

from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages
from pydantic import BaseModel, ConfigDict, Field, field_validator


# 1. PYDANTIC SCHEMAS (BOUNDARY VALIDATION)
# These schemas ensure that data generated by Tools or LLMs
# is mathematically correct before entering the state.


class GrahamMetrics(BaseModel):
    """
    Deterministic Value Investing metrics (Graham Agent).

    This class enforces the "Controlled Degradation" dogma by validating
    numeric values as finite floats and allowing missing metrics as `None`.
    """

    model_config = ConfigDict(frozen=True, populate_by_name=True)

    # Strict ticker validation for market standard compliance.
    ticker: str = Field(
        ...,
        description="O código de negociação do ativo na bolsa B3.",
        pattern=r"^[A-Z0-9]{5,6}$",
    )

    # Campos financeiros obrigatórios para a fórmula de Graham.
    vpa: Optional[float] = Field(
        default=None,
        description="Valor Patrimonial por Ação (VPA).",
    )
    lpa: Optional[float] = Field(
        default=None,
        description="Lucro por Ação (LPA).",
    )

    # Optional fields that depend on calculations or data availability.
    price_to_earnings: Optional[float] = Field(
        default=None,
        description="Índice Preço/Lucro (P/L).",
    )
    fair_value: Optional[float] = Field(
        default=None,
        description="Valor intrínseco calculado pela fórmula de Graham.",
    )
    margin_of_safety: Optional[float] = Field(
        default=None,
        description="Margem de segurança percentual.",
    )

    @field_validator(
        "vpa",
        "lpa",
        "price_to_earnings",
        "fair_value",
        "margin_of_safety",
        mode="before",
    )
    @classmethod
    def validate_finite_float(cls, v: Any) -> Optional[float]:
        """Safely coerces numeric values and rejects NaN/Inf."""
        if v is None:
            return None
        try:
            value = float(v)
        except (TypeError, ValueError) as exc:
            raise ValueError(f"Não foi possível converter o valor '{v}' para float.") from exc

        if not math.isfinite(value):
            raise ValueError(f"O valor '{v}' não é um número finito válido.")

        return value


class FisherAnalysis(BaseModel):
    """Context and sentiment analysis (Fisher Agent)."""

    model_config = ConfigDict(frozen=True)

    sentiment_score: float = Field(
        ...,
        ge=-1,
        le=1,
        description="Pontuação de sentimento extraída das notícias (-1 a 1).",
    )
    key_risks: List[str] = Field(
        ...,
        description="Lista de principais riscos identificados.",
    )
    # Ethical Traceability: Mandatory source citation.
    source_urls: List[str] = Field(
        default_factory=list,
        description="URLs das fontes usadas para a análise.",
    )


class MacroAnalysis(BaseModel):
    """Holistic evaluation of the macroeconomic environment (Macro Agent)."""

    model_config = ConfigDict(frozen=True)

    trend_summary: str = Field(
        ...,
        description="Summary of the current macroeconomic trend.",
    )
    interest_rate_impact: Optional[float] = Field(
        default=None,
        description="Estimated impact of the interest rate (e.g., Selic/Fed Funds).",
    )
    inflation_outlook: Optional[str] = Field(
        None,
        description="Inflation outlook extracted from official minutes.",
    )
    # Ethical Traceability: Mandatory source citation.
    source_urls: List[str] = Field(
        default_factory=list,
        description="URLs das fontes usadas para a análise.",
    )

    @field_validator("interest_rate_impact", mode="before")
    @classmethod
    def validate_finite_float(cls, v: Any) -> Optional[float]:
        """Safely coerces numeric values and rejects NaN/Inf."""
        if v is None:
            return None
        try:
            value = float(v)
        except (TypeError, ValueError) as exc:
            raise ValueError(f"Não foi possível converter o valor '{v}' para float.") from exc

        if not math.isfinite(value):
            raise ValueError(f"O valor '{v}' não é um número finito válido.")

        return value


class PortfolioWeight(BaseModel):
    """Deterministic portfolio weight recommendation per ticker."""

    model_config = ConfigDict(frozen=True)

    ticker: str = Field(
        ...,
        description="The B3 ticker receiving a portfolio allocation.",
        pattern=r"^[A-Z0-9]{5,6}$",
    )
    weight: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Normalized portfolio weight between 0 and 1.",
    )

    @field_validator("weight", mode="before")
    @classmethod
    def validate_finite_float(cls, v: Any) -> float:
        """Safely coerces numeric values and rejects NaN/Inf."""
        try:
            value = float(v)
        except (TypeError, ValueError) as exc:
            raise ValueError(f"Could not convert value '{v}' to float.") from exc

        if not math.isfinite(value):
            raise ValueError(f"Value '{v}' is not a valid finite number.")

        return value


class CoreAnalysis(BaseModel):
    """Supervisor-level deterministic portfolio optimization output."""

    model_config = ConfigDict(frozen=True)

    recommended_weights: List[PortfolioWeight] = Field(
        default_factory=list,
        description="Optimized portfolio allocations for each analyzed ticker.",
    )
    total_risk_score: Optional[float] = Field(
        default=None,
        ge=0.0,
        description="Aggregate portfolio risk score derived from the optimizer output.",
    )
    rational: str = Field(
        ...,
        description="Deterministic rationale for the optimized allocation.",
    )
    source_urls: List[str] = Field(
        default_factory=list,
        description="Consolidated source URLs from specialist agents.",
    )

    @field_validator("total_risk_score", mode="before")
    @classmethod
    def validate_finite_float(cls, v: Any) -> Optional[float]:
        """Safely coerces numeric values and rejects NaN/Inf."""
        if v is None:
            return None
        try:
            value = float(v)
        except (TypeError, ValueError) as exc:
            raise ValueError(f"Could not convert value '{v}' to float.") from exc

        if not math.isfinite(value):
            raise ValueError(f"Value '{v}' is not a valid finite number.")

        return value


# 2. GRAPH STATE DEFINITION (LANGGRAPH)
# The state is the "living object" that circulates among the agents.


class AgentState(BaseModel):
    """
    Representa o Estado Cognitivo Híbrido da Aequitas-MAS.

    Uses Reducers (`operator.add`) to manage the cumulative memory
    in `messages` and `audit_log`, allowing the history to be built
    incrementally with each step of the graph.
    """

    model_config = ConfigDict(frozen=True)

    # History of the conversation between the Supervisor and Specialists.
    messages: Annotated[list[BaseMessage], add_messages] = Field(default_factory=list)

    # Target ticker for the current analysis.
    target_ticker: str = Field(
        ...,
        description="O código de negociação do ativo na bolsa B3.",
        pattern=r"^[A-Z0-9]{5,6}$",
    )

    # Deterministic portfolio optimization inputs.
    portfolio_tickers: List[str] = Field(
        default_factory=list,
        description="Ordered asset universe used by the deterministic optimizer.",
    )
    portfolio_returns: List[List[float]] = Field(
        default_factory=list,
        description="Historical returns aligned with portfolio_tickers.",
    )
    risk_appetite: Optional[float] = Field(
        default=None,
        description="Supervisor-provided risk appetite in the [0, 1] interval.",
    )

    # Decision Tensors (Structured Data).
    # Optional because they are filled progressively.
    # None can indicate 'controlled failure' or 'not yet executed'.
    metrics: Optional[GrahamMetrics] = None
    qual_analysis: Optional[FisherAnalysis] = None
    macro_analysis: Optional[MacroAnalysis] = None
    fisher_rag_score: Optional[float] = None
    macro_rag_score: Optional[float] = None
    marks_verdict: Optional[str] = None
    core_analysis: Optional[CoreAnalysis] = None

    # Audit Log from the Marks Agent (The Devil's Advocate).
    # Annotated + operator.add allows accumulating critiques without overwriting.
    audit_log: Annotated[List[str], operator.add] = Field(default_factory=list)

    # Explicit execution ledger used by the router to avoid re-running nodes.
    executed_nodes: Annotated[List[str], operator.add] = Field(default_factory=list)

    @field_validator("risk_appetite", mode="before")
    @classmethod
    def validate_risk_appetite(cls, v: Any) -> Optional[float]:
        """Safely coerces risk appetite values and rejects NaN/Inf."""
        if v is None:
            return None
        try:
            value = float(v)
        except (TypeError, ValueError) as exc:
            raise ValueError(f"Could not convert value '{v}' to float.") from exc

        if not math.isfinite(value):
            raise ValueError(f"Value '{v}' is not a valid finite number.")

        return value

    @field_validator("fisher_rag_score", "macro_rag_score", mode="before")
    @classmethod
    def validate_optional_unit_interval_score(cls, v: Any) -> Optional[float]:
        """Safely coerce confidence scores and reject NaN/Inf or invalid bounds."""
        if v is None:
            return None
        try:
            value = float(v)
        except (TypeError, ValueError) as exc:
            raise ValueError(f"Could not convert value '{v}' to float.") from exc

        if not math.isfinite(value):
            raise ValueError(f"Value '{v}' is not a valid finite number.")

        if value < 0.0 or value > 1.0:
            raise ValueError(f"Value '{v}' must be within the [0.0, 1.0] interval.")

        return value
